7.10. Истина где-то на сервере v1
htmlacademy-react/1967081-what-to-watch-10 pull request #10
Opened 2022-08-07 20:57 UTC by Cr4zyGleb

2022-08-09 08:32 UTC, ekazakov requested changes

2022-08-09 08:32 UTC, ekazakov commented on project/src/store/api-actions.ts
> +    dispatch(setDataLoadedStatus(true));
1. setDataLoadedStatus(true) надо до вызова api.get 
2. Правильнее назвать этот экшен setDataLoadingStatus и поле в сторе dataLoading — так будет яснее, что это индикатор активного запроса

2022-08-09 08:32 UTC, ekazakov commented on project/src/pages/main-page/main-page.tsx
> +  const loadedFilms = useAppSelector((state) => state.loadedFilms.slice(0, maxRenderedFilmsQuantity));
Еще надо фильтровать фильмы по выбранному жанру и только потом применять `slice(0, maxRenderedFilmsQuantity)`

2022-08-10 08:37 UTC, ekazakov requested changes

2022-08-10 08:37 UTC, ekazakov commented on project/src/pages/main-page/main-page.tsx
> +  const filteredFilms = useAppSelector((state) => state.filteredFilms.slice(0, maxRenderedFilmsQuantity));
Не заметил сразу в сторе не надо хранить отфильтрованные фильмы

Эту логику из редьюсера надо перенести в селектор
```ts
.addCase(changeFilms, (state) => {
      state.filteredFilms = state.loadedFilms.filter((elem) => elem.genre === state.genre || state.genre === GENRES.ALLGENRES);
    })
```

2022-08-10 08:38 UTC, merged

2022-08-10 21:25 UTC, Cr4zyGleb commented on project/src/pages/main-page/main-page.tsx
> +  const filteredFilms = useAppSelector((state) => state.filteredFilms.slice(0, maxRenderedFilmsQuantity));
Не понял что значит из редьюсера в селектор? Селектор это что такое?

2022-08-10 21:29 UTC, Cr4zyGleb commented on project/src/pages/main-page/main-page.tsx
> +  const filteredFilms = useAppSelector((state) => state.filteredFilms.slice(0, maxRenderedFilmsQuantity));
Посмотрел что один раз используются пока что фильтр фильмов, поэтому закинул прям в MainPage
![image](https://user-images.githubusercontent.com/72887137/184023791-6f67708d-bbe9-40b4-bf20-007de8f59804.png)

2022-08-11 07:06 UTC, ekazakov commented on project/src/pages/main-page/main-page.tsx
> +  const filteredFilms = useAppSelector((state) => state.filteredFilms.slice(0, maxRenderedFilmsQuantity));
В селектор, в смысле внутрь useAppSelector. Твой вариант для начала подойдет