Контроль и ограничения (часть 1)
htmlacademy-react/1967081-what-to-watch-10 pull request #8
Opened 2022-07-30 19:02 UTC by Cr4zyGleb

2022-08-01 08:15 UTC, ekazakov requested changes

2022-08-01 08:15 UTC, ekazakov commented on project/src/pages/main-page/main-page.tsx
> +  const stateFilms = useAppSelector((state) => state.films);
Чтобы получить нужные для отображения фильмы можно сделать так:

```tsx
const maxRenderedFilmsQuantity = useAppSelector((state) => state.maxRenderedFilmsQuantity);
const stateFilms = useAppSelector((state) => state.films.slice(0, maxRenderedFilmsQuantity));
```

2022-08-01 08:15 UTC, ekazakov commented on project/src/reducer/reducer.ts
> +      state.maxRenderedFilmsQuantity = maxRenderedFilmsQuantity;
Тут лучше не передавать maxRenderedFilmsQuantity через payload, а просто делать инкремент значения:

```ts
state.maxRenderedFilmsQuantity = Math.min(state.maxRenderedFilmsQuantity + 8, state.films.length);
```

2022-08-01 08:17 UTC, merged

2022-08-02 21:27 UTC, Cr4zyGleb commented on project/src/components/genres-list/genres-list.tsx
> +      <li key={uuidv4()} className={`catalog__genres-item ${ stateGenre === elem ? 'catalog__genres-item--active' : ''}`}>
+

2022-08-02 21:28 UTC, Cr4zyGleb commented on project/src/const.ts
> +  ALLGENRES: 'All genres',
+

2022-08-02 21:28 UTC, Cr4zyGleb commented on project/src/reducer/reducer.ts
> +  genre: 'All genres',
+

2022-08-02 21:30 UTC, Cr4zyGleb commented on project/src/pages/main-page/main-page.tsx
> +  const stateFilms = useAppSelector((state) => state.films);
+

2022-08-02 21:37 UTC, Cr4zyGleb commented on project/src/reducer/reducer.ts
> +      state.maxRenderedFilmsQuantity = maxRenderedFilmsQuantity;
+